[package]
name = "rc5_test"
version = "0.1.0"
authors = ["Mykhailo Kremniov <mkremniov@gmail.com>"]
edition = "2021"

[dependencies]
bytemuck = "1.13.1"
generic-array = "0.14.7"
num = "0.4.0"
zeroize = "1.6.0"
